// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4DboUieSMqUsqxUaUUgYLgYr6CB3rn0',
    appId: '1:345521301448:web:a70b33c1de897258ac82fd',
    messagingSenderId: '345521301448',
    projectId: 'filmaccio',
    authDomain: 'filmaccio.firebaseapp.com',
    storageBucket: 'filmaccio.appspot.com',
    measurementId: 'G-HGRSY356R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsv7bFz-YugncqP4CUdlc0ICcDHiMTdo8',
    appId: '1:345521301448:android:3ad31cf8a2e0310bac82fd',
    messagingSenderId: '345521301448',
    projectId: 'filmaccio',
    storageBucket: 'filmaccio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKAQ-SdMfbOOY_Z40woByB40b_YgbPWg',
    appId: '1:345521301448:ios:ad2879999cb5c8beac82fd',
    messagingSenderId: '345521301448',
    projectId: 'filmaccio',
    storageBucket: 'filmaccio.appspot.com',
    androidClientId: '345521301448-0u06erg3bbjjo6tme4bnkroajodefsh6.apps.googleusercontent.com',
    iosClientId: '345521301448-pa62qhqv90k4p14f01jh7ppk3canr4io.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmaccioFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPKAQ-SdMfbOOY_Z40woByB40b_YgbPWg',
    appId: '1:345521301448:ios:bfabecc3ad9d4fa7ac82fd',
    messagingSenderId: '345521301448',
    projectId: 'filmaccio',
    storageBucket: 'filmaccio.appspot.com',
    androidClientId: '345521301448-0u06erg3bbjjo6tme4bnkroajodefsh6.apps.googleusercontent.com',
    iosClientId: '345521301448-esdsgjpo93em9qmahqqvl6463kqn2shl.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmaccioFlutter.RunnerTests',
  );
}
